question_data = [
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"The Great Wall of China is visible from the moon.","correct_answer":"False","incorrect_answers":["True"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"The Sun rises from the North.","correct_answer":"False","incorrect_answers":["True"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"The color orange is named after the fruit.","correct_answer":"True","incorrect_answers":["False"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"You can legally drink alcohol while driving in Mississippi.","correct_answer":"True","incorrect_answers":["False"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.","correct_answer":"True","incorrect_answers":["False"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"When you cry in space, your tears stick to your face.","correct_answer":"True","incorrect_answers":["False"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"Scotland voted to become an independent country during the referendum from September 2014.","correct_answer":"False","incorrect_answers":["True"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"The National Animal of Scotland is the Unicorn.","correct_answer":"True","incorrect_answers":["False"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"A pasodoble is a type of Italian pasta sauce.","correct_answer":"False","incorrect_answers":["True"]},
        {"category":"General Knowledge","type":"boolean","difficulty":"easy",
        "question":"Slovakia is a member of European Union-","correct_answer":"True","incorrect_answers":["False"]}
]